#! /usr/bin/env node

const program = require('commander');
const inquirer = require('inquirer');
const chalk = require('chalk');
const initProject = require('./action/initProject');

// program
//   .command('service [serviceName]')
//   .alias('s')
//   .description('创建新的service模块')
//   .action(option => {
//     console.log(option);
//   });

program
  .command('init')
  .alias('i')
  .description('初始化新的Spring Cloud微服务项目')
  .action(option => {
    let config = {
      group: null,
      artifact: null,
    };

    // Print version of venus
    console.log(chalk.default.bold('venus v1.0.7'));

    let promps = [];

    if (config.group === null) {
      promps.push({
        type: 'input',
        name: 'group',
        message: '请输入Group',
        validate: input => {
          if (!input) {
            return 'Group不能为空';
          }
          config.group = input;
          return true;
        }
      });
    }

    if (config.artifact === null) {
      promps.push({
        type: 'input',
        name: 'artifact',
        message: '请输入Artifact',
        validate: input => {
          if (!input) {
            return 'Artifact不能为空';
          }
          config.artifact = input;
          return true;
        }
      });
    }

    inquirer.prompt(promps).then(async (answers) => {
      initProject(config);
    });
  });

program.parse(process.argv);
